version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./static/uploads:/app/static/uploads
      - ./models:/app/models
      - ../model_saves_quran_model_final:/app/model_saves_quran_model_final
    environment:
      - FLASK_ENV=production
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quran_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sample_data.sql:/docker-entrypoint-initdb.d/sample_data.sql
      - ../sceheme.sql:/docker-entrypoint-initdb.d/sceheme.sql

volumes:
  mysql_data:
