-- Sample data for Surah An-Naba (Chapter 78) verses
-- Insert sample verses for testing the application

INSERT INTO `quran_id` (`id`, `suraId`, `verseID`, `ayahText`, `indoText`, `readText`) VALUES
(1, 78, 1, 'عَمَّ يَتَسَآءَلُونَ', 'Tentang apakah mereka saling bertanya-tanya?', 'amma yatasaa aluun'),
(2, 78, 2, 'عَنِ ٱلنَّبَإِ ٱلْعَظِيمِ', 'Tentang berita yang besar (hari kebangkitan),', 'an-in nabai-il 'azhiim'),
(3, 78, 3, 'ٱلَّذِى هُمْ فِيهِ مُخْتَلِفُونَ', 'yang dalam hal itu mereka berselisih.', 'alladzii hum fiihi mukhtaliruun'),
(4, 78, 4, 'كَلَّا سَيَعْلَمُونَ', 'Sekali-kali tidak! Kelak mereka akan mengetahui,', 'kallaa saya'lamuun'),
(5, 78, 5, 'ثُمَّ كَلَّا سَيَعْلَمُونَ', 'kemudian sekali-kali tidak! Kelak mereka akan mengetahui.', 'tsumma kallaa saya'lamuun'),
(6, 78, 6, 'أَلَمْ نَجْعَلِ ٱلْأَرْضَ مِهَـٰدًا', 'Bukankah Kami telah menjadikan bumi sebagai hamparan?', 'alam naj'alil ardha mihaadaa'),
(7, 78, 7, 'وَٱلْجِبَالَ أَوْتَادًا', 'Dan gunung-gunung sebagai pasak?', 'wal jibaala autaadaa'),
(8, 78, 8, 'وَخَلَقْنَـٰكُمْ أَزْوَٰجًا', 'Dan Kami menciptakan kamu berpasang-pasangan,', 'wa khalaqnaakum azwaajaa'),
(9, 78, 9, 'وَجَعَلْنَا نَوْمَكُمْ سُبَاتًا', 'dan Kami jadikan tidurmu untuk istirahat,', 'wa ja'alnaa naumakum subaataa'),
(10, 78, 10, 'وَجَعَلْنَا ٱلَّيْلَ لِبَاسًا', 'dan Kami jadikan malam sebagai pakaian,', 'wa ja'alnal laila libaasaa'),
(11, 78, 11, 'وَجَعَلْنَا ٱلنَّهَارَ مَعَاشًا', 'dan Kami jadikan siang untuk mencari penghidupan.', 'wa ja'alnan nahaara ma'aasyaa'),
(12, 78, 12, 'وَبَنَيْنَا فَوْقَكُمْ سَبْعًا شِدَادًا', 'Dan Kami bangun di atas kamu tujuh (langit) yang kokoh,', 'wa banainaa fauqakum sab'an syidaadaa'),
(13, 78, 13, 'وَجَعَلْنَا سِرَاجًا وَهَّاجًا', 'dan Kami jadikan pelita yang sangat terang (matahari),', 'wa ja'alnaa siraaajan wahhaajaa'),
(14, 78, 14, 'وَأَنزَلْنَا مِنَ ٱلْمُعْصِرَٰتِ مَآءً ثَجَّاجًا', 'dan Kami turunkan dari awan air yang tercurah,', 'wa anzalnaa minal mu'shiraati maa-an tsajjaajaa'),
(15, 78, 15, 'لِّنُخْرِجَ بِهِۦ حَبًّا وَنَبَاتًا', 'agar Kami keluarkan dengan air itu biji-bijian dan tumbuh-tumbuhan,', 'linukhrija bihii habban wa nabaataa'),
(16, 78, 16, 'وَجَنَّـٰتٍ أَلْفَافًا', 'dan kebun-kebun yang lebat.', 'wa jannaatin alfaafaa'),
(17, 78, 17, 'إِنَّ يَوْمَ ٱلْفَصْلِ كَانَ مِيقَـٰتًا', 'Sesungguhnya hari keputusan adalah suatu waktu yang ditetapkan,', 'inna yauma al fashli kaana miiqaataa'),
(18, 78, 18, 'يَوْمَ يُنفَخُ فِى ٱلصُّورِ فَتَأْتُونَ أَفْوَاجًا', '(yaitu) hari (yang pada waktu itu) ditiup sangkakala lalu kamu datang berkelompok-kelompok,', 'yauma yunfakhu fii ash shuuri fataatuuna afwaajaa'),
(19, 78, 19, 'وَفُتِحَتِ ٱلسَّمَآءُ فَكَانَتْ أَبْوَٰبًا', 'dan dibukalah langit maka menjadilah ia pintu-pintu,', 'wa futihatissmaau fakanat abwaabaa'),
(20, 78, 20, 'وَسُيِّرَتِ ٱلْجِبَالُ فَكَانَتْ سَرَابًا', 'dan dijalankan gunung-gunung maka menjadilah ia fatamorgana.', 'wa suyyiratal jibaalu fakanat saraabaa'),
(21, 78, 21, 'إِنَّ جَهَنَّمَ كَانَتْ مِرْصَادًا', 'Sesungguhnya Jahannam itu (sebagai) tempat pengintai,', 'inna jahannama kaanat mirshaadaa'),
(22, 78, 22, 'لِّلطَّـٰغِينَ مَـَٔابًا', 'bagi orang-orang yang melampaui batas sebagai tempat kembali,', 'liththaghi ina ma aabaa'),
(23, 78, 23, 'لَّـٰبِثِينَ فِيهَآ أَحْقَابًا', 'mereka kekal di dalamnya beberapa masa.', 'laabitsi ina fiihaaa ahqaabaa'),
(24, 78, 24, 'لَّا يَذُوقُونَ فِيهَا بَرْدًا وَلَا شَرَابًا', 'Di dalamnya mereka tidak merasakan kesejukan dan tidak (pula mendapat) minuman,', 'laa yadzuuquuna fiihaaa bardan wa laa syaraabaa'),
(25, 78, 25, 'إِلَّا حَمِيمًا وَغَسَّاقًا', 'kecuali air yang mendidih dan nanah,', 'illaa hamiiman wa ghassaaqaa'),
(26, 78, 26, 'جَزَآءً وِفَاقًا', 'sebagai pembalasan yang setimpal.', 'jazaa an wifaaqaa'),
(27, 78, 27, 'إِنَّهُمْ كَانُوا۟ لَا يَرْجُونَ حِسَابًا', 'Sesungguhnya mereka tidak takut kepada hisab (pembalasan),', 'innahum kaanuu laa yarjuu na hisaabaa'),
(28, 78, 28, 'وَكَذَّبُوا۟ بِـَٔايَـٰتِنَا كِذَّابًا', 'dan mereka mendustakan ayat-ayat Kami dengan pendustaan (yang keras).', 'wa kadzdzabuu bi aayaatinaa kiddzdzaabaa'),
(29, 78, 29, 'وَكُلَّ شَىْءٍ أَحْصَيْنَـٰهُ كِتَـٰبًا', 'Dan segala sesuatu telah Kami catat dalam kitab.', 'wa kulla syai in ahshaiynaahu kitaabaa'),
(30, 78, 30, 'فَذُوقُوا۟ فَلَن نَّزِيدَكُمْ إِلَّا عَذَابًا', 'Maka rasakanlah azab itu. Kami tidak akan menambah kepada kamu selain azab.', 'fadzuuquu falan nazii dakum illaa 'adzaabaa'),
(31, 78, 31, 'إِنَّ لِلْمُتَّقِينَ مَفَازًا', 'Sesungguhnya orang-orang yang bertakwa mendapat kemenangan,', 'inna lilmuttaqii na mafaazaa'),
(32, 78, 32, 'حَدَآئِقَ وَأَعْنَـٰبًا', '(yaitu) kebun-kebun dan buah anggur,', 'hadaaiq wa a'naabaa'),
(33, 78, 33, 'وَكَوَاعِبَ أَتْرَابًا', 'dan gadis-gadis remaja yang sebaya,', 'wa kawaaba atraabaa'),
(34, 78, 34, 'وَكَأْسًا دِهَاقًا', 'dan gelas-gelas yang penuh (berisi minuman).', 'wa kaasan dihaaqaa'),
(35, 78, 35, 'لَّا يَسْمَعُونَ فِيهَا لَغْوًا وَلَا كِذَّٰبًا', 'Di dalamnya mereka tidak mendengar perkataan yang sia-sia dan tidak (pula perkataan) dusta,', 'laa yasma'uu na fiihaaa laghwan wa laa kiddzdzaabaa'),
(36, 78, 36, 'جَزَآءً مِّن رَّبِّكَ عَطَآءً حِسَابًا', 'sebagai balasan dari Tuhanmu dan pemberian yang cukup,', 'jazaa an min rabbika 'athaa an hisaabaa'),
(37, 78, 37, 'رَّبِّ ٱلسَّمَـٰوَٰتِ وَٱلْأَرْضِ وَمَا بَيْنَهُمَا ٱلرَّحْمَـٰنِ ۖ لَا يَمْلِكُونَ مِنْهُ خِطَابًا', '(dari) Tuhan langit dan bumi dan apa yang ada di antara keduanya, Yang Maha Pemurah. Mereka tidak dapat berbicara dengan Dia.', 'rabbissamaawaati wal ardhi wa maa bainahumar rahmaani laa yamlikuu na minhu khithaabaa'),
(38, 78, 38, 'يَوْمَ يَقُومُ ٱلرُّوحُ وَٱلْمَلَـٰٓئِكَةُ صَفًّا ۖ لَّا يَتَكَلَّمُونَ إِلَّا مَنْ أَذِنَ لَهُ ٱلرَّحْمَـٰنُ وَقَالَ صَوَابًا', 'Pada hari ketika Jibril dan malaikat-malaikat berbaris, mereka tidak berkata-kata kecuali siapa yang telah diberi izin oleh Tuhan Yang Maha Pemurah; dan ia mengucapkan kata yang benar.', 'yauma yaquu mur ruuhu wal malaaikatu shaffal laa yatakallamuuna illaa man adzina lahur rahmaanu wa qaala shawaabaa'),
(39, 78, 39, 'ذَٰلِكَ ٱلْيَوْمُ ٱلْحَقُّ ۖ فَمَن شَآءَ ٱتَّخَذَ إِلَىٰ رَبِّهِۦ مَـَٔابًا', 'Itulah hari yang pasti datang. Maka barangsiapa yang menghendaki, niscaya ia mengambil jalan kembali kepada Tuhannya.', 'dzaalikal yaumul haqqu faman syaa attakhadza ilaa rabbihii ma aabaa'),
(40, 78, 40, 'إِنَّآ أَنذَرْنَـٰكُمْ عَذَابًا قَرِيبًا يَوْمَ يَنظُرُ ٱلْمَرْءُ مَا قَدَّمَتْ يَدَاهُ وَيَقُولُ ٱلْكَافِرُ يَـٰلَيْتَنِى كُنتُ تُرَٰبًۢا', 'Sesungguhnya Kami telah memperingatkan kamu (hai orang kafir) siksa yang dekat, pada hari manusia melihat apa yang telah diperbuat oleh kedua tangannya; dan orang kafir berkata: "Alangkah baiknya sekiranya aku dahulu adalah tanah".', 'innaa andharnaakum 'adzaaban qariiban yauma yanzhuru al mar u maa qaddamat yadaahu wa yaquu lul kaafiru yaalaitanii kuntu turaabaa');
